use_frameworks!

platform :ios, '10.0'

target 'XDFlexKit_Example' do
  pod 'XDFlexKit', :path => '../'

  target 'XDFlexKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
